// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1KmOk9CNTGVAdUzhdYxcuIVdg-MGMkXU',
    appId: '1:1078017879249:web:354131e06798d670cc29f0',
    messagingSenderId: '1078017879249',
    projectId: 'malcolmerp',
    authDomain: 'malcolmerp.firebaseapp.com',
    storageBucket: 'malcolmerp.appspot.com',
    measurementId: 'G-93L9GZ3G8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgdk-23DLoyA6xjS_AmbHcUATYcYQ8WUM',
    appId: '1:1078017879249:android:8de64e681f13579fcc29f0',
    messagingSenderId: '1078017879249',
    projectId: 'malcolmerp',
    storageBucket: 'malcolmerp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgv0tAvaTodAwylGUEgdULs9FxFQ3f3po',
    appId: '1:1078017879249:ios:9bbbf14ad3d7736bcc29f0',
    messagingSenderId: '1078017879249',
    projectId: 'malcolmerp',
    storageBucket: 'malcolmerp.appspot.com',
    iosBundleId: 'com.example.malcolmErp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgv0tAvaTodAwylGUEgdULs9FxFQ3f3po',
    appId: '1:1078017879249:ios:31d8b9cf4e08753ecc29f0',
    messagingSenderId: '1078017879249',
    projectId: 'malcolmerp',
    storageBucket: 'malcolmerp.appspot.com',
    iosBundleId: 'com.example.malcolmErp.RunnerTests',
  );
}
